sonar.projectKey=mahesh-diwan_Mern-Blog-App
sonar.organization=mahesh-diwan
sonar.sources=api,client/src
sonar.exclusions=**/node_modules/**, **/dist/**
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info